### PR TITLE
Add GoogleMutant support

### PR DESCRIPTION
**Pull request by giovanism**
Fixes https://github.com/jieter/leaflet-clonelayer/issues/4

### CODE REVIEW

**Comment by giovanism** [comment]
live version https://giovanism.github.io/Leaflet.layerscontrol-minimap/

**Comment by giovanism** [comment]
The minimap integration is still not perfect tho, something triggers the fullscreen button

**Comment by jieter** [comment]
Hi @giovanism, thanks for the pull! As you can see, the tests fail. We do not use ES6 yet, so please write this using `var`. I also suspect the tests will fail if `L.GridLayer.GoogleMutant` is not available, which should be taken care of by changing line 39 to:
```
if (L.GridLayer.GoogleMutant && layer instanceof L.GridLayer.GoogleMutant) {
```

I don't really understand the `layer._GAPIPromise.then`-part. Is this required to clone the layer?

> The minimap integration is still not perfect tho, something triggers the fullscreen button

I tried a couple of times, but did not manage to not trigger the layer in a way not leading to a (non-functioning) fullscreen map, it also shows an error message in the minimap:
screen shot 2018-07-09 at 16 15 56

But let's fix the cloning part first...

**Comment by giovanism** [comment]
Ok, I can amend them.

`layer._GAPIPromise.then` part is necessary to re-add added googleLayerss/subLayers from googleMutant. As their current implementation, `addGoogleLayer` is asynchronous. So it has to wait the process to complete before I can clone them.

Google Maps API gives error message when used without API_KEY.

You can select the layer by clicking the radiobutton on the corner of the map.

**Comment by jieter** [comment]
Looks good, thanks.

**Pull request merged**
