### PR TITLE
Add support for WMS TileLayer

### PR DESCRIPTION
**Pull request by mhasbie**
[TileLayer.WMS](http://leafletjs.com/reference-1.3.0.html#tilelayer-wms)

### CODE REVIEW

**Comment by jieter** [comment]
Hi @mhasbie, thanks opening a PR. Are you sure this is a problem?
I think this line is not necessary as [`L.TileLayer.WMS` extends from `L.TileLayer`](https://github.com/Leaflet/Leaflet/blob/018bac0e9e7446426c6127e16bb6baed566b8a7f/src/layer/tile/TileLayer.WMS.js#L25) and the implementation of the actual cloning is equal for both `L.TileLayer` and `L.TileLayer.WMS`.

Or did you experience problems using leaflet-clonelayer with `L.TileLayer.WMS`? If so, can you share a jsfiddle or something like that?

**Comment by mhasbie** [comment]
@jieter, yes i can confirm this. A WMS tile layer needs to be instantiated using `L.tileLayer.wms` since WMS service url are constructed differently than of Tile Layer.

The following fiddles demonstrates this. I'm using `react-leaflet-magnifying-glass` and `leaflet-clonelayer` to clone the layers to the magnifying glass layer instance.

JSFiddles:
[With WMS Tile Layer support](https://jsfiddle.net/m_hasbie/vdn3opxp/) - this works. All base layers are cloned to the magnifying glass.

[Without WMS Tile Layer support](https://jsfiddle.net/m_hasbie/m7qhha9b/) - this doesn't work. the wms base layer are not cloned to the magnifying glass. Other Tile layers still works.

Thanks!

**Comment by jieter** [comment]
You are right off course, it needs to be called with the correct constructor.

**Comment by jieter** [comment]
Merged, thanks

**Comment by jieter** [comment]
released leaflet-clonelayer@1.0.5

**Pull request merged**
